fork-wait:
	gcc fork-wait.c -o fork-wait && ./fork-wait && rm ./fork-wait

signals:
	gcc signals.c -o signals && ./signals && rm ./signals

alarms:
	gcc alarms.c -o alarms && ./alarms && rm ./alarms

bad-exec:
	gcc bad-exec.c -o bad-exec && ./bad-exec && rm ./bad-exec

good-exec:
	gcc good-exec.c -o good-exec && ./good-exec && rm ./good-exec

clone-fork:
	gcc clone-fork.c -o clone-fork && ./clone-fork && rm ./clone-fork